<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0-windows</TargetFramework>
		<UseWindowsForms>true</UseWindowsForms>
		<OutputType>Library</OutputType>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
	</PropertyGroup>

	<ItemGroup>
	  <Compile Remove="Documentation\**" />
	  <Compile Remove="Examples\**" />
	  <EmbeddedResource Remove="Documentation\**" />
	  <EmbeddedResource Remove="Examples\**" />
	  <None Remove="Documentation\**" />
	  <None Remove="Examples\**" />
	</ItemGroup>

	<ItemGroup>
	  <Compile Remove="CustomControls\ModerContextMenuStrip.cs" />
	  <Compile Remove="CustomControls\ModernButton00.cs" />
	  <Compile Remove="CustomControls\ModernDataGridView.cs" />
	  <Compile Remove="CustomControls\ModernErrorProvider.cs" />
	  <Compile Remove="CustomControls\ModernFormDesigner.cs" />
	  <Compile Remove="CustomControls\ModernFormStyle.cs" />
	  <Compile Remove="CustomControls\ModernPanel.cs" />
	  <Compile Remove="CustomControls\notification.cs" />
	  <Compile Remove="CustomControls\notification.Designer.cs" />
	</ItemGroup>

	<ItemGroup>
	  <EmbeddedResource Remove="CustomControls\notification.resx" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Properties\" />
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Include="Microsoft.Data.SqlClient" Version="5.2.2" />
	</ItemGroup>

</Project>