<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<RootNamespace>DVLD.BLL</RootNamespace>
		<AssemblyName>DVLD.BLL</AssemblyName>
		<LangVersion>latest</LangVersion>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>

		<AnalysisLevel>latest-recommended</AnalysisLevel>
		<EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
	</PropertyGroup>

	<ItemGroup>
	  <Compile Remove="Services\Partial\**" />
	  <EmbeddedResource Remove="Services\Partial\**" />
	  <None Remove="Services\Partial\**" />
	</ItemGroup>

	<ItemGroup>
	  <Compile Remove="Common\SearchCriteria.cs" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="DTOs\NewFolder\" />
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Include="Microsoft.Data.SqlClient" Version="5.2.2" />
	</ItemGroup>

	<ItemGroup>
	  <Reference Include="DVLD.DAL">
	    <HintPath>..\@Data_Access_Layer_(DAL)\bin\Debug\net10.0\DVLD.DAL.dll</HintPath>
	  </Reference>
	</ItemGroup>

</Project>