<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<RootNamespace>DVLD.BLL</RootNamespace>
		<AssemblyName>DVLD.BLL</AssemblyName>
		<LangVersion>latest</LangVersion>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>

		<AnalysisLevel>latest-recommended</AnalysisLevel>
		<EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\@Data_Access_Layer_(DAL)\DVLD.DAL.csproj" />
	</ItemGroup>

</Project>