<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net10.0-windows</TargetFramework>
		<UseWindowsForms>true</UseWindowsForms>
		<RootNamespace>DVLD.PL</RootNamespace>
		<AssemblyName>DVLD.PL</AssemblyName>
		<LangVersion>14.0</LangVersion>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<Deterministic>true</Deterministic>
		<AnalysisLevel>latest-recommended</AnalysisLevel>
		<EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
	</PropertyGroup>

	<ItemGroup>
		<Compile Remove="Managementيشسب\**" />
		<Compile Remove="People\**" />
		<Compile Remove="Resources\**" />
		<Compile Remove="UsersManagement\**" />
		<EmbeddedResource Remove="Managementيشسب\**" />
		<EmbeddedResource Remove="People\**" />
		<EmbeddedResource Remove="Resources\**" />
		<EmbeddedResource Remove="UsersManagement\**" />
		<None Remove="Managementيشسب\**" />
		<None Remove="People\**" />
		<None Remove="Resources\**" />
		<None Remove="UsersManagement\**" />
	</ItemGroup>

	<ItemGroup>
		<Compile Remove="clsSearch.cs" />
		<Compile Remove="frmDashboard.cs" />
		<Compile Remove="frmDashboard.Designer.cs" />
		<Compile Remove="Shared.cs" />
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Remove="frmDashboard.resx" />
	</ItemGroup>

	<ItemGroup>
		<None Remove=".gitignore" />
		<None Remove="Management\Drivers\Forms\frmAddNewDriver.Designer.cs~RFc6932bb.TMP" />
	</ItemGroup>

	<ItemGroup>
		<Compile Update="Properties\Resources.Designer.cs">
			<DesignTime>True</DesignTime>
			<AutoGen>True</AutoGen>
			<DependentUpon>Resources.resx</DependentUpon>
		</Compile>
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Update="Properties\Resources.resx">
			<Generator>ResXFileCodeGenerator</Generator>
			<LastGenOutput>Resources.Designer.cs</LastGenOutput>
		</EmbeddedResource>
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Common\Theme\SettingsTheme\" />
	</ItemGroup>
<ItemGroup>
    <ProjectReference Include="..\Custom-WinForm-Controls\CustomizeControls.csproj" />
    <ProjectReference Include="..\Business-Logic-Layer\DVLD.BLL.csproj" />
</ItemGroup>
</Project>