<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<RootNamespace>DVLD.DAL</RootNamespace>
		<AssemblyName>DVLD.DAL</AssemblyName>
		<LangVersion>latest</LangVersion>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>

		<AnalysisLevel>latest-recommended</AnalysisLevel>
		<EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
	</PropertyGroup>

	<ItemGroup>
	  <Compile Remove="Common\clsCRUD.cs" />
	  <Compile Remove="Entities\Application.cs" />
	  <Compile Remove="Entities\ApplicationType.cs" />
	  <Compile Remove="Entities\Country.cs" />
	  <Compile Remove="Entities\DetainedLicense.cs" />
	  <Compile Remove="Entities\Driver.cs" />
	  <Compile Remove="Entities\InternationalLicense.cs" />
	  <Compile Remove="Entities\License.cs" />
	  <Compile Remove="Entities\LicenseClass.cs" />
	  <Compile Remove="Entities\LocalDrivingLicenseApplication.cs" />
	  <Compile Remove="Entities\Test.cs" />
	  <Compile Remove="Entities\TestAppointment.cs" />
	  <Compile Remove="Entities\TestType.cs" />
	  <Compile Remove="Entities\User.cs" />
	  <Compile Remove="Repositories\AdoNet\ApplicationRepository.cs" />
	  <Compile Remove="Repositories\AdoNet\ApplicationTypeRepository.cs" />
	  <Compile Remove="Repositories\AdoNet\CountryRepository.cs" />
	  <Compile Remove="Repositories\AdoNet\DetainedLicenseRepository.cs" />
	  <Compile Remove="Repositories\AdoNet\DriverRepository.cs" />
	  <Compile Remove="Repositories\AdoNet\InternationalLicenseRepository.cs" />
	  <Compile Remove="Repositories\AdoNet\LicenseClassRepository.cs" />
	  <Compile Remove="Repositories\AdoNet\LicenseRepository.cs" />
	  <Compile Remove="Repositories\AdoNet\LocalDrivingLicenseApplicationRepository.cs" />
	  <Compile Remove="Repositories\AdoNet\TestAppointmentRepository.cs" />
	  <Compile Remove="Repositories\AdoNet\TestRepository.cs" />
	  <Compile Remove="Repositories\AdoNet\TestTypeRepository.cs" />
	  <Compile Remove="Repositories\AdoNet\UserRepository.cs" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Data.SqlClient" Version="5.2.2" />
	</ItemGroup>

</Project>