<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net10.0-windows</TargetFramework>
		<UseWindowsForms>true</UseWindowsForms>
		<RootNamespace>DVLD.PL</RootNamespace>
		<AssemblyName>DVLD.PL</AssemblyName>
		<LangVersion>10.0</LangVersion>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<ApplicationManifest>app.manifest</ApplicationManifest>
		<Deterministic>true</Deterministic>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\@Business_Logic_Layer_(BLL)\DVLD_BusinessLogicLayer.csproj" />
		<ProjectReference Include="..\@Custom_Controls\ApplicatinNeededControlsModern.csproj" />
	</ItemGroup>

</Project>