<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net10.0-windows</TargetFramework>
		<UseWindowsForms>true</UseWindowsForms>
		<RootNamespace>DVLD.PL</RootNamespace>
		<AssemblyName>DVLD.PL</AssemblyName>
		<LangVersion>10.0</LangVersion>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<ApplicationManifest>app.manifest</ApplicationManifest>
		<Deterministic>true</Deterministic>
		<ApplicationIcon>ChatGPT Image Aug 18, 2026, 11_09_30 AM.ico</ApplicationIcon>
	</PropertyGroup>

	<ItemGroup>
	  <Content Include="ChatGPT Image Aug 18, 2026, 11_09_30 AM.ico" />
	</ItemGroup>

	<ItemGroup>
	  <Reference Include="ApplicatinNeededControlsModern">
	    <HintPath>..\@Custom_Controls\bin\Debug\ApplicatinNeededControlsModern.dll</HintPath>
	  </Reference>
	  <Reference Include="DVLD.BLL">
	    <HintPath>..\@Business_Logic_Layer_(BLL)\bin\Debug\net10.0\DVLD.BLL.dll</HintPath>
	  </Reference>
	</ItemGroup>

</Project>